export interface PrintProfile {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: 'consultation' | 'comparison' | 'research' | 'book';
  pageSize: 'A4' | 'Letter' | 'Legal' | 'A5';
  orientation: 'portrait' | 'landscape';
  margins: { top: number; right: number; bottom: number; left: number };
  density: 'compact' | 'standard' | 'detailed';
  fontSize: number;
  lineHeight: number;
  paragraphSpacing: number;
  includeCoverPage: boolean;
  includeTOC: boolean;
  includeExecutiveSummary: boolean;
  includeAppendices: boolean;
  includeFormulaTransparency: boolean;
  includeCalibrationTransparency: boolean;
  pageNumbers: boolean;
  headers: boolean;
  footers: boolean;
  bookmarks: boolean;
  chapterNumbers: boolean;
  pdfQuality: 'standard' | 'high' | 'print';
  embedFonts: boolean;
  colorProfile: 'sRGB' | 'CMYK';
}

const PRINT_PROFILES: Record<string, PrintProfile> = {
  'quick-consultation': {
    id: 'quick-consultation',
    name: 'Quick Consultation',
    description: 'Minimal pages, core insights only',
    icon: 'zap',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 20, right: 20, bottom: 20, left: 25 },
    density: 'compact',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: false,
    includeTOC: false,
    includeExecutiveSummary: true,
    includeAppendices: false,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: false,
    chapterNumbers: false,
    pdfQuality: 'standard',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'professional-consultation': {
    id: 'professional-consultation',
    name: 'Professional Consultation',
    description: 'Complete client-ready report',
    icon: 'file-text',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
  'research-report': {
    id: 'research-report',
    name: 'Research Report',
    description: 'Maximum detail for analysis',
    icon: 'microscope',
    category: 'research',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'detailed',
    fontSize: 10,
    lineHeight: 1.6,
    paragraphSpacing: 8,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'comparison-report': {
    id: 'comparison-report',
    name: 'Comparison Report',
    description: 'Side-by-side chart comparison',
    icon: 'git-compare',
    category: 'comparison',
    pageSize: 'A4',
    orientation: 'landscape',
    margins: { top: 20, right: 20, bottom: 20, left: 20 },
    density: 'standard',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'book-format': {
    id: 'book-format',
    name: 'Book Format',
    description: 'Bound publication layout',
    icon: 'book-open',
    category: 'book',
    pageSize: 'A5',
    orientation: 'portrait',
    margins: { top: 30, right: 25, bottom: 30, left: 35 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
};

export const PRINT_PROFILES = {
  'quick-consultation': {
    id: 'quick-consultation',
    name: 'Quick Consultation',
    description: 'Minimal pages, core insights only',
    icon: 'zap',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 20, right: 20, bottom: 20, left: 25 },
    density: 'compact',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: false,
    includeTOC: false,
    includeExecutiveSummary: true,
    includeAppendices: false,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: false,
    chapterNumbers: false,
    pdfQuality: 'standard',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'professional-consultation': {
    id: 'professional-consultation',
    name: 'Professional Consultation',
    description: 'Complete client-ready report',
    icon: 'file-text',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
  'research-report': {
    id: 'research-report',
    name: 'Research Report',
    description: 'Maximum detail for analysis',
    icon: 'microscope',
    category: 'research',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'detailed',
    fontSize: 10,
    lineHeight: 1.6,
    paragraphSpacing: 8,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'comparison-report': {
    id: 'comparison-report',
    name: 'Comparison Report',
    description: 'Side-by-side chart comparison',
    icon: 'git-compare',
    category: 'comparison',
    pageSize: 'A4',
    orientation: 'landscape',
    margins: { top: 20, right: 20, bottom: 20, left: 20 },
    density: 'standard',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'book-format': {
    id: 'book-format',
    name: 'Book Format',
    description: 'Bound publication layout',
    icon: 'book-open',
    category: 'book',
    pageSize: 'A5',
    orientation: 'portrait',
    margins: { top: 30, right: 25, bottom: 30, left: 35 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
};

export const PRINT_PROFILES = {
  'quick-consultation': {
    id: 'quick-consultation',
    name: 'Quick Consultation',
    description: 'Minimal pages, core insights only',
    icon: 'zap',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 20, right: 20, bottom: 20, left: 25 },
    density: 'compact',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: false,
    includeTOC: false,
    includeExecutiveSummary: true,
    includeAppendices: false,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: false,
    chapterNumbers: false,
    pdfQuality: 'standard',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'professional-consultation': {
    id: 'professional-consultation',
    name: 'Professional Consultation',
    description: 'Complete client-ready report',
    icon: 'file-text',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
  'research-report': {
    id: 'research-report',
    name: 'Research Report',
    description: 'Maximum detail for analysis',
    icon: 'microscope',
    category: 'research',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'detailed',
    fontSize: 10,
    lineHeight: 1.6,
    paragraphSpacing: 8,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'comparison-report': {
    id: 'comparison-report',
    name: 'Comparison Report',
    description: 'Side-by-side chart comparison',
    icon: 'git-compare',
    category: 'comparison',
    pageSize: 'A4',
    orientation: 'landscape',
    margins: { top: 20, right: 20, bottom: 20, left: 20 },
    density: 'standard',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'book-format': {
    id: 'book-format',
    name: 'Book Format',
    description: 'Bound publication layout',
    icon: 'book-open',
    category: 'book',
    pageSize: 'A5',
    orientation: 'portrait',
    margins: { top: 30, right: 25, bottom: 30, left: 35 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
};

export const PRINT_PROFILES = {
  'quick-consultation': {
    id: 'quick-consultation',
    name: 'Quick Consultation',
    description: 'Minimal pages, core insights only',
    icon: 'zap',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 20, right: 20, bottom: 20, left: 25 },
    density: 'compact',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: false,
    includeTOC: false,
    includeExecutiveSummary: true,
    includeAppendices: false,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: false,
    chapterNumbers: false,
    pdfQuality: 'standard',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'professional-consultation': {
    id: 'professional-consultation',
    name: 'Professional Consultation',
    description: 'Complete client-ready report',
    icon: 'file-text',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
  'research-report': {
    id: 'research-report',
    name: 'Research Report',
    description: 'Maximum detail for analysis',
    icon: 'microscope',
    category: 'research',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'detailed',
    fontSize: 10,
    lineHeight: 1.6,
    paragraphSpacing: 8,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'comparison-report': {
    id: 'comparison-report',
    name: 'Comparison Report',
    description: 'Side-by-side chart comparison',
    icon: 'git-compare',
    category: 'comparison',
    pageSize: 'A4',
    orientation: 'landscape',
    margins: { top: 20, right: 20, bottom: 20, left: 20 },
    density: 'standard',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'book-format': {
    id: 'book-format',
    name: 'Book Format',
    description: 'Bound publication layout',
    icon: 'book-open',
    category: 'book',
    pageSize: 'A5',
    orientation: 'portrait',
    margins: { top: 30, right: 25, bottom: 30, left: 35 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
};

export const PRINT_PROFILES = {
  'quick-consultation': {
    id: 'quick-consultation',
    name: 'Quick Consultation',
    description: 'Minimal pages, core insights only',
    icon: 'zap',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 20, right: 20, bottom: 20, left: 25 },
    density: 'compact',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: false,
    includeTOC: false,
    includeExecutiveSummary: true,
    includeAppendices: false,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: false,
    chapterNumbers: false,
    pdfQuality: 'standard',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'professional-consultation': {
    id: 'professional-consultation',
    name: 'Professional Consultation',
    description: 'Complete client-ready report',
    icon: 'file-text',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
  'research-report': {
    id: 'research-report',
    name: 'Research Report',
    description: 'Maximum detail for analysis',
    icon: 'microscope',
    category: 'research',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'detailed',
    fontSize: 10,
    lineHeight: 1.6,
    paragraphSpacing: 8,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'comparison-report': {
    id: 'comparison-report',
    name: 'Comparison Report',
    description: 'Side-by-side chart comparison',
    icon: 'git-compare',
    category: 'comparison',
    pageSize: 'A4',
    orientation: 'landscape',
    margins: { top: 20, right: 20, bottom: 20, left: 20 },
    density: 'standard',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'book-format': {
    id: 'book-format',
    name: 'Book Format',
    description: 'Bound publication layout',
    icon: 'book-open',
    category: 'book',
    pageSize: 'A5',
    orientation: 'portrait',
    margins: { top: 30, right: 25, bottom: 30, left: 35 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
};

export const PRINT_PROFILES = {
  'quick-consultation': {
    id: 'quick-consultation',
    name: 'Quick Consultation',
    description: 'Minimal pages, core insights only',
    icon: 'zap',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 20, right: 20, bottom: 20, left: 25 },
    density: 'compact',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: false,
    includeTOC: false,
    includeExecutiveSummary: true,
    includeAppendices: false,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: false,
    chapterNumbers: false,
    pdfQuality: 'standard',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'professional-consultation': {
    id: 'professional-consultation',
    name: 'Professional Consultation',
    description: 'Complete client-ready report',
    icon: 'file-text',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
  'research-report': {
    id: 'research-report',
    name: 'Research Report',
    description: 'Maximum detail for analysis',
    icon: 'microscope',
    category: 'research',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'detailed',
    fontSize: 10,
    lineHeight: 1.6,
    paragraphSpacing: 8,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'comparison-report': {
    id: 'comparison-report',
    name: 'Comparison Report',
    description: 'Side-by-side chart comparison',
    icon: 'git-compare',
    category: 'comparison',
    pageSize: 'A4',
    orientation: 'landscape',
    margins: { top: 20, right: 20, bottom: 20, left: 20 },
    density: 'standard',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'book-format': {
    id: 'book-format',
    name: 'Book Format',
    description: 'Bound publication layout',
    icon: 'book-open',
    category: 'book',
    pageSize: 'A5',
    orientation: 'portrait',
    margins: { top: 30, right: 25, bottom: 30, left: 35 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
};

export const PRINT_PROFILES = {
  'quick-consultation': {
    id: 'quick-consultation',
    name: 'Quick Consultation',
    description: 'Minimal pages, core insights only',
    icon: 'zap',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 20, right: 20, bottom: 20, left: 25 },
    density: 'compact',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: false,
    includeTOC: false,
    includeExecutiveSummary: true,
    includeAppendices: false,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: false,
    chapterNumbers: false,
    pdfQuality: 'standard',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'professional-consultation': {
    id: 'professional-consultation',
    name: 'Professional Consultation',
    description: 'Complete client-ready report',
    icon: 'file-text',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
  'research-report': {
    id: 'research-report',
    name: 'Research Report',
    description: 'Maximum detail for analysis',
    icon: 'microscope',
    category: 'research',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'detailed',
    fontSize: 10,
    lineHeight: 1.6,
    paragraphSpacing: 8,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'comparison-report': {
    id: 'comparison-report',
    name: 'Comparison Report',
    description: 'Side-by-side chart comparison',
    icon: 'git-compare',
    category: 'comparison',
    pageSize: 'A4',
    orientation: 'landscape',
    margins: { top: 20, right: 20, bottom: 20, left: 20 },
    density: 'standard',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'book-format': {
    id: 'book-format',
    name: 'Book Format',
    description: 'Bound publication layout',
    icon: 'book-open',
    category: 'book',
    pageSize: 'A5',
    orientation: 'portrait',
    margins: { top: 30, right: 25, bottom: 30, left: 35 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
};

export const PRINT_PROFILES = {
  'quick-consultation': {
    id: 'quick-consultation',
    name: 'Quick Consultation',
    description: 'Minimal pages, core insights only',
    icon: 'zap',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 20, right: 20, bottom: 20, left: 25 },
    density: 'compact',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: false,
    includeTOC: false,
    includeExecutiveSummary: true,
    includeAppendices: false,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: false,
    chapterNumbers: false,
    pdfQuality: 'standard',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'professional-consultation': {
    id: 'professional-consultation',
    name: 'Professional Consultation',
    description: 'Complete client-ready report',
    icon: 'file-text',
    category: 'consultation',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
  'research-report': {
    id: 'research-report',
    name: 'Research Report',
    description: 'Maximum detail for analysis',
    icon: 'microscope',
    category: 'research',
    pageSize: 'A4',
    orientation: 'portrait',
    margins: { top: 25, right: 25, bottom: 25, left: 30 },
    density: 'detailed',
    fontSize: 10,
    lineHeight: 1.6,
    paragraphSpacing: 8,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'comparison-report': {
    id: 'comparison-report',
    name: 'Comparison Report',
    description: 'Side-by-side chart comparison',
    icon: 'git-compare',
    category: 'comparison',
    pageSize: 'A4',
    orientation: 'landscape',
    margins: { top: 20, right: 20, bottom: 20, left: 20 },
    density: 'standard',
    fontSize: 10,
    lineHeight: 1.4,
    paragraphSpacing: 4,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: true,
    includeCalibrationTransparency: true,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'high',
    embedFonts: true,
    colorProfile: 'sRGB',
  },
  'book-format': {
    id: 'book-format',
    name: 'Book Format',
    description: 'Bound publication layout',
    icon: 'book-open',
    category: 'book',
    pageSize: 'A5',
    orientation: 'portrait',
    margins: { top: 30, right: 25, bottom: 30, left: 35 },
    density: 'standard',
    fontSize: 11,
    lineHeight: 1.5,
    paragraphSpacing: 6,
    includeCoverPage: true,
    includeTOC: true,
    includeExecutiveSummary: true,
    includeAppendices: true,
    includeFormulaTransparency: false,
    includeCalibrationTransparency: false,
    pageNumbers: true,
    headers: true,
    footers: true,
    bookmarks: true,
    chapterNumbers: true,
    pdfQuality: 'print',
    embedFonts: true,
    colorProfile: 'CMYK',
  },
};